"""One-time, deterministic hardening patch for backend/server.py.

This script exists because the server file is large and the GitHub contents API
only supports full-file replacement. It fails loudly if the expected source
shape changes, preventing a partial or ambiguous patch.
"""
from pathlib import Path

# Keep this script deterministic: each replacement must match exactly once.
PATH = Path(__file__).resolve().parents[1] / "backend" / "server.py"
text = PATH.read_text(encoding="utf-8")


def replace_once(old: str, new: str) -> None:
    global text
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"Expected exactly one match, found {count}: {old[:120]!r}")
    text = text.replace(old, new, 1)


replace_once("import logging\n", "import logging\nimport hmac\n")

replace_once(
    "STRIPE_API_KEY = os.environ['STRIPE_API_KEY']\n",
    "STRIPE_API_KEY = os.environ['STRIPE_API_KEY']\n"
    "APP_ENV = os.environ.get('APP_ENV', 'development').strip().lower()\n"
    "DEMO_MODE_ENABLED = os.environ.get('DEMO_MODE_ENABLED', 'false').strip().lower() == 'true'\n"
    "ALLOW_UNVERIFIED_STOREKIT = (\n"
    "    os.environ.get('ALLOW_UNVERIFIED_STOREKIT', 'false').strip().lower() == 'true'\n"
    ")\n",
)

replace_once(
    "plaid_client = plaid_api.PlaidApi(plaid.ApiClient(plaid_config))\n",
    "plaid_client = plaid_api.PlaidApi(plaid.ApiClient(plaid_config))\n\n"
    "def _plaid_configured() -> bool:\n"
    "    invalid = {'', 'not-configured', 'your-plaid-client-id', 'your-plaid-secret'}\n"
    "    return PLAID_CLIENT_ID not in invalid and PLAID_SECRET not in invalid\n",
)

replace_once("password: str = Field(min_length=6)", "password: str = Field(min_length=12)")
replace_once('app = FastAPI(title="TaxHaul API")', 'app = FastAPI(title="Milli API")')
replace_once('client_name="TaxHaul",', 'client_name="Milli",')
replace_once(
    "async def plaid_link_token(user: dict = Depends(get_current_user)):\n    req = LinkTokenCreateRequest(",
    "async def plaid_link_token(user: dict = Depends(get_current_user)):\n"
    "    if not _plaid_configured():\n"
    "        raise HTTPException(status_code=503, detail='Plaid is not configured')\n"
    "    req = LinkTokenCreateRequest(",
)
replace_once(
    "async def plaid_exchange(body: PublicTokenIn, user: dict = Depends(get_current_user)):\n    try:",
    "async def plaid_exchange(body: PublicTokenIn, user: dict = Depends(get_current_user)):\n"
    "    if not _plaid_configured():\n"
    "        raise HTTPException(status_code=503, detail='Plaid is not configured')\n"
    "    try:",
)

replace_once("You are TaxHaul AI, a tax assistant", "You are Milli AI, a tax assistant")
replace_once("Prepared by TaxHaul  |", "Prepared by Milli  |")
replace_once(
    "This is a worksheet generated by TaxHaul.",
    "This is a worksheet generated by Milli.",
)

replace_once(
    '@api.post("/demo/seed")\nasync def demo_seed():\n    """Create or refresh demo user \'Jordan Taylor\' and return a token."""',
    '@api.post("/demo/seed")\nasync def demo_seed(request: Request):\n'
    '    """Create or refresh the demo account in explicitly enabled local environments."""\n'
    '    if APP_ENV == "production" or not DEMO_MODE_ENABLED:\n'
    '        raise HTTPException(status_code=404, detail="Not found")\n'
    '    expected_secret = os.environ.get("DEMO_SEED_SECRET", "")\n'
    '    supplied_secret = request.headers.get("X-Demo-Seed-Secret", "")\n'
    '    if not expected_secret or not hmac.compare_digest(supplied_secret, expected_secret):\n'
    '        raise HTTPException(status_code=403, detail="Invalid demo seed secret")',
)

replace_once(
    "    except HTTPException:\n"
    "        # Fallback: trust the client transactionId only in Sandbox/dev\n"
    "        if APPLE_IAP_ENV.lower() != \"production\":\n"
    "            logging.warning(\"Apple IAP creds missing — accepting sandbox txn %s optimistically\", body.transactionId)\n"
    "            plan = IAP_PRODUCT_TO_PLAN.get(body.productId or \"\", \"pro\")\n",
    "    except HTTPException:\n"
    "        # Unverified StoreKit is never allowed in production and must be\n"
    "        # explicitly enabled for local/TestFlight development.\n"
    "        if APP_ENV != \"production\" and ALLOW_UNVERIFIED_STOREKIT:\n"
    "            plan = IAP_PRODUCT_TO_PLAN.get(body.productId or \"\")\n"
    "            if not plan:\n"
    "                raise HTTPException(status_code=400, detail=\"Unknown StoreKit product\")\n"
    "            logging.warning(\"Accepting explicitly enabled unverified sandbox txn %s\", body.transactionId)\n",
)

replace_once(
    "async def verify_apple_receipt(body: IAPValidateIn, user: dict = Depends(get_current_user)):\n",
    "async def verify_apple_receipt(body: IAPValidateIn, user: dict = Depends(get_current_user)):\n"
    "    if not body.transactionId or not body.transactionId.strip():\n"
    "        raise HTTPException(status_code=400, detail=\"Missing transactionId\")\n"
    "    if body.productId and body.productId not in IAP_PRODUCT_TO_PLAN:\n"
    "        raise HTTPException(status_code=400, detail=\"Unknown StoreKit product\")\n",
)

replace_once(
    "async def apple_iap_webhook(request: Request):\n    \"\"\"\n",
    "async def apple_iap_webhook(request: Request):\n"
    "    if APP_ENV == \"production\":\n"
    "        # The current implementation does not yet validate Apple's x5c JWS\n"
    "        # certificate chain. Reject production webhooks rather than trust\n"
    "        # attacker-controlled unsigned claims.\n"
    "        raise HTTPException(status_code=503, detail=\"Verified Apple webhook handling is not configured\")\n"
    "    \"\"\"\n",
)

replace_once(
    "app.add_middleware(\n"
    "    CORSMiddleware,\n"
    "    allow_credentials=True,\n"
    "    allow_origins=os.environ.get('CORS_ORIGINS', '*').split(','),\n"
    "    allow_methods=[\"*\"],\n"
    "    allow_headers=[\"*\"],\n"
    ")\n",
    "_cors_origins = [\n"
    "    origin.strip()\n"
    "    for origin in os.environ.get('CORS_ORIGINS', 'http://localhost:3000').split(',')\n"
    "    if origin.strip()\n"
    "]\n"
    "if APP_ENV == 'production' and '*' in _cors_origins:\n"
    "    raise RuntimeError('Wildcard CORS is forbidden in production')\n\n"
    "app.add_middleware(\n"
    "    CORSMiddleware,\n"
    "    allow_credentials=True,\n"
    "    allow_origins=_cors_origins,\n"
    "    allow_methods=[\"*\"],\n"
    "    allow_headers=[\"*\"],\n"
    ")\n",
)

PATH.write_text(text, encoding="utf-8")
print(f"Hardened {PATH}")
