from pathlib import Path

ROOT = Path.cwd()


def load(path: str) -> str:
    return (ROOT / path).read_text()


def save(path: str, text: str) -> None:
    (ROOT / path).write_text(text)


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected 1 match, found {count}")
    return text.replace(old, new, 1)


pbx_path = "frontend/ios/App/App.xcodeproj/project.pbxproj"
pbx = load(pbx_path)
if "SceneDelegate.swift in Sources" not in pbx:
    pbx = replace_once(pbx, "\t\t504EC3081FED79650016851F /* AppDelegate.swift in Sources */ = {isa = PBXBuildFile; fileRef = 504EC3071FED79650016851F /* AppDelegate.swift */; };\n", "\t\t504EC3081FED79650016851F /* AppDelegate.swift in Sources */ = {isa = PBXBuildFile; fileRef = 504EC3071FED79650016851F /* AppDelegate.swift */; };\n\t\tA6C202600000000000000001 /* SceneDelegate.swift in Sources */ = {isa = PBXBuildFile; fileRef = A6C202600000000000000002 /* SceneDelegate.swift */; };\n", "PBXBuildFile")
    pbx = replace_once(pbx, "\t\t504EC3071FED79650016851F /* AppDelegate.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = AppDelegate.swift; sourceTree = \"<group>\"; };\n", "\t\t504EC3071FED79650016851F /* AppDelegate.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = AppDelegate.swift; sourceTree = \"<group>\"; };\n\t\tA6C202600000000000000002 /* SceneDelegate.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = SceneDelegate.swift; sourceTree = \"<group>\"; };\n", "PBXFileReference")
    pbx = replace_once(pbx, "\t\t\t\t504EC3071FED79650016851F /* AppDelegate.swift */,\n", "\t\t\t\t504EC3071FED79650016851F /* AppDelegate.swift */,\n\t\t\t\tA6C202600000000000000002 /* SceneDelegate.swift */,\n", "PBXGroup")
    pbx = replace_once(pbx, "\t\t\t\t504EC3081FED79650016851F /* AppDelegate.swift in Sources */,\n", "\t\t\t\t504EC3081FED79650016851F /* AppDelegate.swift in Sources */,\n\t\t\t\tA6C202600000000000000001 /* SceneDelegate.swift in Sources */,\n", "PBXSourcesBuildPhase")
    save(pbx_path, pbx)

server_path = "backend/server.py"
server = load(server_path)
server = server.replace("# IRS 2026 standard mileage rate (approx, configurable)\nIRS_MILEAGE_RATE = 0.70\nSE_TAX_RATE = 0.153  # Self-employment tax\n", "SE_TAX_RATE = 0.153  # Self-employment tax\n", 1)
server = replace_once(server, "    deductible = round(miles * IRS_MILEAGE_RATE, 2)\n", "    from tax_engine import mileage_rate_for_date\n    trip_date = trip.get(\"start_time\") or date.today().isoformat()\n    mileage_rate = mileage_rate_for_date(trip_date, \"business\", int(str(trip_date)[:4]))\n    deductible = round(miles * mileage_rate, 2)\n", "end trip mileage")
server = replace_once(server, "            \"deductible_value\": deductible,\n            \"points\": [p.dict() for p in (body.points or [])],\n", "            \"deductible_value\": deductible,\n            \"mileage_rate\": mileage_rate,\n            \"points\": [p.dict() for p in (body.points or [])],\n", "end trip rate storage")
server = replace_once(server, "        \"deductible_value\": round(miles * IRS_MILEAGE_RATE, 2),\n        \"manual\": True,\n", "        \"deductible_value\": round(\n            miles * __import__(\"tax_engine\").mileage_rate_for_date(body.date, \"business\", int(str(body.date)[:4])),\n            2,\n        ),\n        \"mileage_rate\": __import__(\"tax_engine\").mileage_rate_for_date(body.date, \"business\", int(str(body.date)[:4])),\n        \"manual\": True,\n", "manual trip mileage")
server = replace_once(server, "    from tax_engine import (\n        IRS_MILEAGE_RATE_BUSINESS,\n        IRS_MILEAGE_RATE_MEDICAL,\n        IRS_MILEAGE_RATE_CHARITABLE,\n    )\n", "    from tax_engine import mileage_rate_for_date\n", "classification import")
server = replace_once(server, "    rate = {\n        \"business\": IRS_MILEAGE_RATE_BUSINESS,\n        \"medical\": IRS_MILEAGE_RATE_MEDICAL,\n        \"charitable\": IRS_MILEAGE_RATE_CHARITABLE,\n    }.get(body.classification, 0.0)\n", "    trip_date = trip.get(\"start_time\") or trip.get(\"date\") or trip.get(\"created_at\")\n    rate = mileage_rate_for_date(trip_date, body.classification, int(str(trip_date or date.today().isoformat())[:4]))\n", "classification rate")
server = replace_once(server, "        \"deductible_value\": deductible,\n        \"reviewed_at\": datetime.now(timezone.utc).isoformat(),\n", "        \"deductible_value\": deductible,\n        \"mileage_rate\": rate,\n        \"reviewed_at\": datetime.now(timezone.utc).isoformat(),\n", "classification storage")
server = replace_once(server, "    from tax_engine import mileage_deduction\n", "    from tax_engine import mileage_deduction_for_trips\n", "summary import")
server = replace_once(server, "    biz = sum(t[\"miles\"] for t in trips if _bucket(t) == \"business\")\n    med = sum(t[\"miles\"] for t in trips if _bucket(t) == \"medical\")\n    cha = sum(t[\"miles\"] for t in trips if _bucket(t) == \"charitable\")\n    review_count = sum(1 for t in trips if _bucket(t) == \"needs_review\")\n\n    return {\n        \"year\": year,\n        **mileage_deduction(biz, med, cha),\n        \"trips_count\": len(trips),\n        \"trips_needing_review\": review_count,\n    }\n", "    review_count = sum(1 for t in trips if _bucket(t) == \"needs_review\")\n    summary = mileage_deduction_for_trips(trips, year)\n\n    return {\n        \"year\": year,\n        **summary,\n        \"trips_count\": len(trips),\n        \"trips_needing_review\": review_count,\n    }\n", "summary body")
server = replace_once(server, "    gross = sum(d[\"amount\"] for d in deposits)\n    miles = sum(t.get(\"miles\", 0) for t in trips)\n    mileage_deduction = round(miles * IRS_MILEAGE_RATE, 2)\n    expense_total = sum(e[\"amount\"] for e in expenses)\n    net_income = max(0.0, gross - mileage_deduction - expense_total)\n\n    se_tax = round(net_income * SE_TAX_RATE, 2)\n    state_rate = STATE_TAX_RATES.get(user.get(\"state\", \"TX\"), 0.0)\n    # Approximate fed income tax on top of SE @ a simple 12% bracket\n    fed_income_tax = round(max(0.0, net_income - se_tax/2) * 0.12, 2)\n    state_tax = round(net_income * state_rate, 2)\n    estimated_tax = round(se_tax + fed_income_tax + state_tax, 2)\n", "    from tax_engine import calc_total_tax, mileage_deduction_for_trips, mileage_rates_for_date, profile_from_user\n\n    gross = sum(d[\"amount\"] for d in deposits)\n    mileage = mileage_deduction_for_trips(trips, year)\n    miles = mileage[\"business_miles\"] + mileage[\"medical_miles\"] + mileage[\"charitable_miles\"]\n    mileage_deduction = mileage[\"total_deduction\"]\n    expense_total = sum(e[\"amount\"] for e in expenses)\n    profile = profile_from_user({**user, \"tax_year\": year})\n    tax = calc_total_tax(gross, mileage_deduction + expense_total, profile)\n    net_income = tax.net_earnings_from_se\n    se_tax = tax.se_tax\n    fed_income_tax = tax.federal_income_tax\n    state_tax = tax.state_income_tax\n    state_rate = STATE_TAX_RATES.get(user.get(\"state\", \"TX\"), 0.0)\n    estimated_tax = tax.total_tax\n    year_end_rates = mileage_rates_for_date(date(year, 12, 31), year)\n", "tax summary")
server = replace_once(server, "        \"irs_mileage_rate\": IRS_MILEAGE_RATE,\n", "        \"irs_mileage_rate\": year_end_rates[\"business\"],\n        \"irs_mileage_rate_periods\": mileage[\"rate_periods\"],\n", "summary response")
server = replace_once(server, "            f\"situations. The current IRS standard mileage rate is ${IRS_MILEAGE_RATE}/mi.\"\n", "            \"situations. Mileage rates can change during a tax year, so always use the trip date when calculating a deduction.\"\n", "AI prompt")
server = replace_once(server, "    c.drawString(70, y, f\"9. Car & truck (standard mileage {summary['total_miles']:.1f} mi @ ${IRS_MILEAGE_RATE}/mi): ${summary['mileage_deduction']:,.2f}\"); y -= 14\n", "    c.drawString(70, y, f\"9. Car & truck (date-aware standard mileage; {summary['total_miles']:.1f} mi): ${summary['mileage_deduction']:,.2f}\"); y -= 14\n", "worksheet label")
server = replace_once(server, "            \"deductible_value\": round(miles * IRS_MILEAGE_RATE, 2),\n            \"manual\": True,\n", "            \"deductible_value\": round(miles * __import__(\"tax_engine\").mileage_rate_for_date(d_date, \"business\", d_date.year), 2),\n            \"mileage_rate\": __import__(\"tax_engine\").mileage_rate_for_date(d_date, \"business\", d_date.year),\n            \"manual\": True,\n", "demo mileage")
server = replace_once(server, "    trips = await db.trips.find(q, {\"_id\": 0}).to_list(5000)\n    trips = [t for t in trips if str(t.get(\"date\", \"\")).startswith(str(y))]\n    business_miles = round(sum(float(t.get(\"miles\", 0)) for t in trips), 1)\n    mileage_deduction = round(business_miles * 0.70, 2)\n", "    from tax_engine import mileage_deduction_for_trips\n\n    trips = await db.trips.find(q, {\"_id\": 0}).to_list(5000)\n    trips = [t for t in trips if str(t.get(\"start_time\") or t.get(\"date\") or \"\").startswith(str(y))]\n    mileage = mileage_deduction_for_trips(trips, y)\n    business_miles = mileage[\"business_miles\"]\n    mileage_deduction = mileage[\"business_deduction\"]\n", "schedule C")
if "IRS_MILEAGE_RATE" in server:
    raise RuntimeError("Legacy IRS_MILEAGE_RATE references remain")
save(server_path, server)

Path("backend/tests/test_2026_tax_constants.py").write_text('''from datetime import date\nfrom tax_engine import FED_BRACKETS_2026, QBI_INCOME_LIMIT_2026, SS_WAGE_BASE_2026, STANDARD_DEDUCTION_2026, TaxProfile, calc_federal_income_tax, calc_se_tax, calc_total_tax, mileage_deduction, mileage_deduction_for_trips, mileage_rates_for_date\n\ndef test_2026_constants():\n    assert FED_BRACKETS_2026["single"][0] == (0.10, 12_400)\n    assert FED_BRACKETS_2026["single"][-2] == (0.35, 640_600)\n    assert FED_BRACKETS_2026["married_joint"][-2] == (0.35, 768_700)\n    assert FED_BRACKETS_2026["married_separate"][-2] == (0.35, 384_350)\n    assert STANDARD_DEDUCTION_2026 == {"single": 16_100, "married_joint": 32_200, "married_separate": 16_100, "head_of_household": 24_150, "qualifying_widow": 32_200}\n    assert QBI_INCOME_LIMIT_2026["married_joint"] == 403_500\n    assert SS_WAGE_BASE_2026 == 184_500.0\n\ndef test_2026_se_and_federal_tax():\n    se_tax, _ = calc_se_tax(300_000, TaxProfile(tax_year=2026))\n    assert se_tax == round(184_500 * 0.124 + (300_000 * 0.9235) * 0.029, 2)\n    assert calc_federal_income_tax(60_000, "single", 2026) == round(12_400 * .10 + (50_400 - 12_400) * .12 + (60_000 - 50_400) * .22, 2)\n    assert calc_total_tax(100_000, 10_000, TaxProfile(home_state="TX", tax_year=2026)).federal_income_tax > 0\n\ndef test_2026_mileage_boundary():\n    assert mileage_rates_for_date(date(2026, 6, 30))["business"] == 0.725\n    assert mileage_rates_for_date(date(2026, 7, 1))["business"] == 0.76\n    assert mileage_deduction(100, trip_date="2026-06-30", tax_year=2026)["business_deduction"] == 72.50\n    assert mileage_deduction(100, trip_date="2026-07-01", tax_year=2026)["business_deduction"] == 76.00\n    trips = [{"start_time": "2026-06-30T12:00:00Z", "classification": "business", "miles": 100}, {"start_time": "2026-07-01T12:00:00Z", "classification": "business", "miles": 100}]\n    assert mileage_deduction_for_trips(trips, 2026)["business_deduction"] == 148.50\n''')

workflow_path = ".github/workflows/validate.yml"
workflow = load(workflow_path).replace("pytest -q tests/test_phase2_engine.py tests/test_2025_tax_constants.py", "pytest -q tests/test_phase2_engine.py tests/test_2025_tax_constants.py tests/test_2026_tax_constants.py", 1)
save(workflow_path, workflow)
Path(".github/workflows/inspect-2026-tax-usage.yml").unlink(missing_ok=True)
